### ISSUE TITLE
Parenthesis wrap

### ISSUE THREAD

**Issue by thomasahle** [j4mie/idiorm#187]
When writing `or` conditions like

```
where_raw('(`age` = ? OR `age` = ?)', array(20, 25))
```

It would be nice not having to add the parentheses around the whole query. This could be easily achived, and would save the developer for the doubt 'did I need parentheses here or not?'

**Comment by ionrink** [comment]
I strongly agree with the bug reporter. It is natural to think that the where_raw() SQL will be evaluated without mixing with SQL from other filtering functions. The other filtering functions do not involve the developer writing SQL, all of that is handled on the backend by Idiorm.

Anyone relying on their raw SQL to mix with Idiorm's generated SQL would be relying on Idiorm's generated SQL to be identical across releases. That is clearly a bad idea and breaks the logical separation between the app and Idiorm.

Backwards compatibility is important, but relying on user supplied SQL to combine with Idiorm generated SQL was always wrong and no one should have been doing that to start with. Always adding parentheses prevents the developer from making that mistake and I believe should be seen as enforcing good coding practices that all developers should be doing anyway.
