### ISSUE TITLE
Join multiple condition syntax

### ISSUE THREAD

**Issue by nicolas-t** [j4mie/idiorm#194]
Hi,

I'd like to do a join based on multiple criteria.

It works fine with the non-escaped method : 

``` php
->left_outer_join('fav', '(post.id = fav.post_id) AND (fav.user_id = '.$id.')')
```

How to do the same join using the escaped method ?

thank you :)

**Comment by Erutan409** [comment]
I'm curious why this was closed without answering the last documentation question.  I, too, have looked this over and it's not very straight-forward; at least to @nicolas-t (at the time) and I.

**Comment by treffynnon** [comment]
This is a three year old ticket. I've got no idea. Perhaps I got an email
from them. Maybe I just didn't see their question.
