### ISSUE TITLE
More then one where_raw 

### ISSUE THREAD

**Issue by onlysli** [j4mie/idiorm#236]
Hi,
It seems that i can't use more then one where_raw in one statement. Only the first one is working, the second one is ignored.

Is there a fix for this?

Thank you!

**Comment by treffynnon** [comment]
I have written a test to verify this and I cannot replicate the issue you're having. Please see https://github.com/j4mie/idiorm/blob/develop/test/QueryBuilderTest.php#L295

If you run the test suite and still get failures please open a new ticket.
