### ISSUE TITLE
Delete on table where primary key is a combination of two fields

### ISSUE THREAD

**Issue by Razinsky** [j4mie/idiorm#246]
Hi, first of, Idiorm/Paris is AWESOME!

That said, I'm having an issue right now where I want to delete a row in a table where the primary key is a unique combination of two fields. Looking at the code I understand that Idiorm does not support that. So my question is: What is the best way to accomplish it? Overriding the delete method and crafting a raw query? Is there a "sexier" way to do it that I haven't thought?

Thanks!

**Comment by rafamds** [comment]
I also wanted to know how to achieve this? Any progress?

**Comment by lrlopez** [comment]
Support for compound primary keys was added some months ago. You can see how it works in this example:
```php
ORM::for_table('folder_delivery')->
        use_id_column(array('folder_id', 'delivery_id'))->
        where_in('folder_id', $folders)->
        where_null('snapshot_id')->
        find_result_set()->
        set('snapshot_id', $snapId)->
        save();
```
The primary key table `folder_delivery` is the combination of `folder_id` and `delivery_id`. This query will select the records that belong to one of the folders stored in `$folders` and that have null in the field `snapshot_id`. Then, it will change the value and save them.

I hope it helps.

**Comment by rafamds** [comment]
You have to override that table `id's` using `ORM::configure`, like so:

```php
ORM::configure('id_column_overrides', array(
    'stickers_stats' => array('user_id', 'sticker_id', 'event_id')
));
```

And then, use `find_one()` with an array, like so:

```php
$stats = ORM::for_table('stickers_stats')->find_one(array(
    'user_id' => $user->id,
    'sticker_id' => $id,
    'event_id' => $event->id
));

$stats->delete();
```

You can check more information on compound keys here:
http://idiorm.readthedocs.org/en/latest/configuration.html#id1
