### ISSUE TITLE
Multiple Likes in Query

### ISSUE THREAD

**Issue by redaxmedia** [j4mie/idiorm#259]
Hello,

I have a question about the most accurate way to use Idiorm with multiple likes:

<pre>'title LIKE \'%' . $value . '%\' || description LIKE \'%' . $value . '%\' || keywords LIKE \'%' . $value . '%\' || text LIKE \'%' . $value . '%\''</pre>

The <code>where_like</code> does not support this kind of query in my opinion. Should I use <code>where_raw</code> or extend Idiorm using something like:

<pre>
// this is not working, just an idea
public function where_any_like($column_name, $values) {
return $this->_add_where_placeholder($column_name, 'LIKE', $values);
}
</pre>

Thank you

**Comment by redaxmedia** [comment]
I wrote something like for my Db class that extends from ORM:

<pre>
/**
 * where like clause with many
 *
* @since 2.3.0
 *
 * @param array $column array of column names
 * @param array $values array of values
 *
 * @return Db
 */
public function whereLikeMany($column = null, $values = null)
{
	if (is_array($column) && is_array($values))
	{
		return $this->whereRaw(implode($column, ' LIKE ? OR ') . ' LIKE ?', $values);
	}
	else
	{
		return $this;
	}
}
</pre>

That can be called that way:

<pre>
->whereLikeMany(array(
	'title',
	'description',
	'keywords',
	'text'
), array(
	'%' . $search . '%',
	'%' . $search . '%',
	'%' . $search . '%',
	'%' . $search . '%'
))
</pre>


Please let me know, if there is a better way...

**Comment by ranjitWBS** [comment]
hi
I have used this , added above function to my ORM class. But it still not working, Can you help me out?
here is my code
`$d = ORM::for_table('sys_invoices')->table_alias('q')->select('q.*')->select('l.id', 'lid')->select('l.name', 'name')->join('sys_locations', array('q.locid', '=', 'l.id'),"l")->where('q.eid',$user['id'])->whereLikeMany(array('truck_license_no','trailer_license_no','truck_no','trailer_no'),array('%'.$license_no.'%','%'.$license_no.'%','%'.$vehicle_no.'%','%'.$vehicle_no.'%'))->offset($paginator['startpoint'])->limit($paginator['limit'])->order_by_desc('q.id')->find_many();`
Waiting for your replay 
Thanks

**Comment by redaxmedia** [comment]
You have to write your own class that includes the new method, it is not part of Idiorm.

Something like that, remove the methods that are not needed:
https://github.com/redaxmedia/redaxscript/blob/3.0.0/includes/Db.php
