### ISSUE TITLE
find_one() behavior with NULL parametr

### ISSUE THREAD

**Issue by tssk** [j4mie/idiorm#261]
Hello,

ORM::for_table('my_table')->find_one() method without any parametr selects some one record.

But for some reason I expected that ORM::for_table('my_table')->find_one(NULL) will return false or error. But idiorm does not behave this way and also returns the same as in the first example.

On the other hand ORM::for_table('my_table')->where('id', NULL)->find_one() returns false.

Sorry for maybe stupid question but is my expectation bad? It would seem more intuitive to me.

Thanks,

Tomas

**Comment by treffynnon** [comment]
http://idiorm.readthedocs.org/en/latest/querying.html#working-with-null-values-where-null-and-where-not-null

**Comment by tssk** [comment]
@treffynnon,
the link you posted is something else than what I was trying to explain.

I am lazy so I thought that I might use idiorm / find_one() for cheching request parameters in silex.

ORM::for_table('my_table')->find_one($app['request']->get('id')); //when id is not set get() method will return NULL. So this is why I would welcome that idiorm would make difference between callin find_one() and find_one(NULL).

But when I know how it behaves know I am just fine using following construction which behaves as I expect:  
ORM::for_table('my_table')->where('id', $app['request']->get('id'))->find_one();

I just wanted to share in case you would find it as useful behavior.

Regards,

Tomas
