### ISSUE TITLE
Workaround PDO::PARAM_BOOL being broken since 2006

### ISSUE THREAD

**Issue by 1player** [j4mie/idiorm#264]
Details: Ubuntu, MySQL

Passing a boolean type to PDO causes the query to fail silently.
That is a known PDO bug reported since 2006 and not fixed yet.

http://stackoverflow.com/questions/10242312/pdo-bindvalue-with-pdoparam-bool-causes-statement-execute-to-fail-silently
https://bugs.php.net/bug.php?id=38546
https://bugs.php.net/bug.php?id=66632

I spent 30 minutes trying to investigate why my row wasn't inserted when I set a boolean field to TRUE or FALSE. While it works when I set it to 0 or 1.

Until the PHP deities decide to fix it, the only known workaround is to use PARAM_INT for boolean types too.

**Comment by 1player** [comment]
Why was this closed? Unless my bug report is unclear, this issue affects idiorm. That's how I got bitten by it.

**Comment by treffynnon** [comment]
It's not related to Idiorm and belongs as an issue on the upstream project.

**Comment by Addvilz** [comment]
Indeed. If we would start to fix upstream stuff here, we probably would need to abstract away all of the php. Not really lightweight.
