### ISSUE TITLE
lastInsertId not supported for ODBC

### ISSUE THREAD

**Issue by WoLfulus** [j4mie/idiorm#266]
I'm using ODBC to connect to a SQL Server instance and PDO::lastInsertId() is not supported. 
For several reasons I cannot use sqlsrv or dblib. What would be the proper way to implement the different lastInsertId() inside idiorm?

Thanks!

**Comment by treffynnon** [comment]
Doubt that the PDO driver for ODBC supports `lastInsertId` which would make this outside of the realms of Idiorms control.

http://stackoverflow.com/questions/781677/php-get-the-last-insert-id-from-odbc-connection might have a solution for you.

**Comment by WoLfulus** [comment]
well, yeah, I had the solution already, maybe it wasn't clear on the question, but I just wanted to know how to do the "proper" integration into Idiorm to get the last id for ODBC (with custom configs maybe?).

Anyways, thanks.
