### ISSUE TITLE
Issue with is_dirty

### ISSUE THREAD

**Issue by tentwofour** [j4mie/idiorm#267]
Using Idiorm with Paris; I have a model from which I need to determine if a subset of fields has changed. When setting any of those values to '', or null, the _dirty_fields property is set as such:

``` php
_dirty_fields: [
changed_field => 'a new value'
changed_field_set_to_null => 
]
```

So it knows that 'changed_field_set_to_null' is dirty, and persists it properly. However, asking my model if the property is dirty returns false:

``` php
public function save()
{
    if ($this->is_dirty('changed_field_set_to_null')) // false
    {
        // Do stuff
    }
}
```

Looking in idiorm.php, at the is_dirty method, on line 1966:

``` php
public function is_dirty($key) {
    return isset($this->_dirty_fields[$key]);
}
```

Changing that to correctly triggers that the field is dirty (but not sure if that affects other use-cases, it shouldn't, I don't think...)

``` php
public function is_dirty($key) {
    return array_key_exists($key, $this->_dirty_fields);
}
```

The field in question is a one-to-one relation with another table, the FK is defined on the main table, and setup via 'belongs_to' in my Paris model. Everything works and persists properly, I just can't tell if that one field is actually dirty...

I feel I may be missing something obvious here?

**Comment by Addvilz** [comment]
This seems like a bug, actually.

**Comment by tentwofour** [comment]
PR's accepted for bugs?

**Comment by treffynnon** [comment]
Yes they are.

**Comment by tag** [comment]
PRs get more consideration when they include unit tests and documentation.
