### ISSUE TITLE
id() returns string

### ISSUE THREAD

**Issue by dwelle** [j4mie/idiorm#269]
Is there a reason why `id()` does not respect the datatype of the primary id column? Especially when `PDO::ATTR_EMULATE_PREPARES` is set to `false`.

```
$elem = ORM::for_table('test')->create();
$elem->set('title', 'Bob Smith')->save();
var_dump( $elem->id() ); // e.g. -> string(2) "97"
```

**Comment by treffynnon** [comment]
Cos that's what PDO returns.

**Comment by dwelle** [comment]
Well, I'll be damned. Shame on me. Thanks.
