### ISSUE TITLE
Use natural SQLite primary key

### ISSUE THREAD

**Issue by GhaziTriki** [j4mie/idiorm#270]
Hello,

I have been trying to update an SQLite record using the default primary key but I get an excpetion probably because the default columns "rowid" was never fetched.

```
PHP Fatal error:  Uncaught exception 'Exception' with message
'Primary key ID missing from row or is null' in /vagrant/vendor/j4mie/idiorm/idiorm.php:1909
```

According to SQLite documentation in the below link the rowid is accessible via "rowid", "oid", or "_rowid_.
https://www.sqlite.org/lang_createtable.html

Do you have any idea if this can be implemented? It means that prior to update is should be fetched in the select query.

**Comment by treffynnon** [comment]
idiorm assumes your primary key column is called id if not then you must
specify the primary key. See
http://idiorm.readthedocs.org/en/latest/configuration.html#id-column
