### ISSUE TITLE
Non static usage

### ISSUE THREAD

**Issue by codecowboy** [j4mie/idiorm#271]
If I want to reuse a configured connection, what pattern would you recommend for using it throughout a small application? Use a singleton? The objective is to not have to repeat calls to ```ORM::configure()```

I may also need multiple connections so maybe a factory would be better. Are there any examples of this anywhere?

**Comment by tag** [comment]
See the documentation on multiple connections for examples. All of the queries accept an optional trailing parameter that specifies the connection using a string key.

You should only have to use `ORM::configure()` once.

**Comment by codecowboy** [comment]
"You should only have to use ORM::configure() once." That's what I thought but it was not true in my use case. I am developing a WordPress plugin which needs access to a legacy database. 

If I called ORM::Configure in plugin code, it was not available in templates. e.g.:

```$job = ORM::for_table('jobs_ol')->where('job_ref', (int) $wp_query->get('job'))->find_one();``` resulted in:
```Uncaught exception 'PDOException' with message 'could not find driver'```

However, ensuring that ORM::Configure() was called earlier in the plugin execution chain resolved this for me. In case others are using idiorm and WordPress Plugin Boilerplate, this meant ensuring it was called by the main plugin file's constructor.

**Comment by treffynnon** [comment]
I don't know much of WordPress plugin development, but it seems to me there
shouldn't be any queries from templates anyway unless I am misunderstanding
terminology here. Either way I am glad you got it sorted out.
