### ISSUE TITLE
How can I use “where_not_like” for more than a value? 

### ISSUE THREAD

**Issue by rosorrentino** [j4mie/idiorm#273]
Hi

I have a quick question, I am doing a query and want to use “where_not_like” for values from an array, is this possible to use more than a value of an array for where_not_like? 

I am trying to add it, but I can’t even using implode to add %% between values, but looks like “where_not_like” is only for one value.

Any tips? 

Thanks in advance.

**Comment by treffynnon** [comment]
```php
$q = ORM::for_table('my_table');
foreach($items as $item) {
    $q->where_not_like($item);
}
$results = $q->find_many();
```

**Comment by rosorrentino** [comment]
Thanks a lot!
