### ISSUE TITLE
Problem when save HTML content

### ISSUE THREAD

**Issue by hermans** [j4mie/idiorm#275]
Hello, i got problem when save html content from wysiwyg tool.

content source:
 “On the Air”
and
ccc’s

and when i check in database it  â€œOn the Airâ€  and cccâ€™s

**Comment by peter-mw** [comment]
This is not Idiorm issue, its encoding issue. 

I have used idiorm to save pages in many languages.

Check if your database is using UTF-8 and check also if your PHP script is in UTF too. 

Make sure all your files are saved as UTF-8 without BOM

**Comment by hermans** [comment]
ok, thanks. let me try it
