### ISSUE TITLE
Is there any method like where_any_is but using like? 

### ISSUE THREAD

**Issue by rosorrentino** [j4mie/idiorm#276]
HI, I am looking in documentation for a option as where_any_is or where_in but to use as “like” so I can use wildcards in the search values (same as use WHERE x LIKE y OR x LIKE z); 

I think this methods “where_any_is" or “where_in" are very useful since we can give arrays and the number of inputs are variable.

**Comment by JoN1oP** [comment]
Hi @rosorrentino,
This is how I solved this particular problem. I created a filter on my model.
```php
static function search($orm, $search = '') {
  if(strlen(trim($search) === 0)) {
    return $orm;
  }

  return $orm->where_raw(
    '(`email` LIKE ? OR `first_name` LIKE ? OR `last_name` LIKE ?)',
    array('%'.$search.'%', '%'.$search.'%', '%'.$search.'%')
  );
}
```

**Comment by rosorrentino** [comment]
Thanks, I will try that, much appreciate it.

**Comment by treffynnon** [comment]
This is the route to do this kind of thing with Idiorm.
