### ISSUE TITLE
Provide method to actually run a raw query

### ISSUE THREAD

**Issue by aaronpk** [j4mie/idiorm#277]
Right now it looks like raw_query is expected to be used with `find_one()` or `find_many()` which means it can't be used for a query like an update or other non-select query. It would be great if I could do something like `ORM::execute('UPDATE users SET active = 0')` and it would just run that query and not expect any results to be returned.

**Comment by treffynnon** [comment]
Would [`raw_execute()`](https://github.com/j4mie/idiorm/blob/master/idiorm.php#L387) suit your needs?

**Comment by aaronpk** [comment]
oh yes, I think it would work. I didn't see it mentioned in the "raw query" section of the docs: https://idiorm.readthedocs.org/en/latest/querying.html

**Comment by treffynnon** [comment]
Please feel free to submit a pull request improving the docs.
