### ISSUE TITLE
issue when primary id is not named 'id' but is used as 'id'

### ISSUE THREAD

**Issue by cwhsu1984** [j4mie/idiorm#278]
Hi,

I have a table 'article' and the primary key is 'article_id', when I use idiorm like this:
`ORM::for_table('article')->select('article.article_id', 'id')->limit(3)->find_many();`
It gives the following error messages:
>... vendor/j4mie/idiorm/idiorm.php:429, ERRNO:2, PDOStatement::execute(): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1

However, if I modify the query like this:
`ORM::for_table('article')->select_expr('article.article_id as id')->limit(3)->find_many();`
Then everything goes fine, I think this might be a bug for this special condition.

**Comment by limenet** [comment]
This is probably related to this assumption (from [the docs](https://idiorm.readthedocs.org/en/latest/configuration.html#id-column)):

> By default, the ORM assumes that all your tables have a primary key column called `id`. There are two ways to override this: for all tables in the database, or on a per-table basis.

You could try something like this:

```php
ORM::configure('id_column_overrides', [
    'article' => 'article_id',
]);
```
(taken from the same link as above)

Also, you could have a look at the query Idiorm produced and start debugging from there. You can retrieve the last query using `ORM::get_last_query()`.

**Comment by lrlopez** [comment]
@cwhsu1984 Linus is right, you must override the id column name. You can also use the fluent query interface for that:
```php
ORM::for_table('article')->use_id_column('article_id')->select('article.article_id', 'id')->limit(3)->find_many();
```

**Comment by cwhsu1984** [comment]
@limenet @lrlopez It's a bit late, but you guys are correct. And in fact, I find that I am seeing the same error message when using where_in('item.uuid', $arr)  with empty $arr. It's a bit confused.
