### ISSUE TITLE
How can I use UNION within Idiorm?

### ISSUE THREAD

**Issue by martinburch** [j4mie/idiorm#281]
Is this going to require `raw_query()` or is there something I'm overlooking? I can't find "union" mentioned in the docs.

**Comment by hailie-rei** [comment]
I have the same question. It seems there's no union in the code at all now, but can somebody give an example how to implement this the best way? Thanks!

**Comment by tegansnyder** [comment]
Do it with `raw_query`. Example:

```php
$sql = <<<SQL
	SELECT a.* FROM table_name_a a
	UNION ALL
	SELECT b.* FROM table_name_b b
SQL;

$recs = ORM::for_table('table_name_here_a')
    ->raw_query($sql)
    ->find_array();
```
