### ISSUE TITLE
PDO DBLIB for MS SQL having problems with " (double quote) quote character

### ISSUE THREAD

**Issue by nbpalomino** [j4mie/idiorm#286]
When working with pdo_dblib for connect to MS SQL Server 2008, 

Idiorm uses " (double quote) as quote character but this produces query errors on Red Hat Server with PHP5.2 and above mentioned SQL Server.

I fixed using none quote character. As follows:

```php
    protected static function _detect_identifier_quote_character($connection_name) {
        switch(self::get_db($connection_name)->getAttribute(PDO::ATTR_DRIVER_NAME)) {
            case 'pgsql':
            case 'sqlsrv':
            //case 'dblib':
            case 'mssql':
            case 'sybase':
            case 'firebird':
                return '"';
            case 'dblib':
                return '';
            case 'mysql':
            case 'sqlite':
            case 'sqlite2':
            default:
                return '`';
        }
    }
```

Also I fixed a `PDO::lastInsertId()` for PDO_dblib as follows:

```php
if($driver == 'dblib') {
    // MS SQL SERVER's driver "pdo_dblib" doesn't have PDO::lastInsertId();
    $stmt = $db->prepare("SELECT SCOPE_IDENTITY() AS id");
     if($stmt->execute()) {
         $row = $stmt->fetch();
         $this->_data[$column] = $row['id'];
      }
  } else {
      $this->_data[$column] = $db->lastInsertId();
  }
```

Im preparing a Pull Request for this fixes if is valid off course.

Thanks.

**Comment by bradrozier** [comment]
Concerning your pdo_dblib quoting issues, I recall having similar issues with SQL server when first using idiorm a while ago. I may have tried the solution you've proposed, but I think that created some other issues. What we ended up doing was to add this to our connection block when connection to SQL server:

`ORM::raw_execute('SET QUOTED_IDENTIFIER ON');`

Hope it helps.

**Comment by treffynnon** [comment]
Quoting will not be turned off in Idiorm. You need to enable it on your
server or connect request.

**Comment by nbpalomino** [comment]
Ok about Quote Character I will use *ORM::raw_execute('SET QUOTED_IDENTIFIER ON');* .

But, what about *PDO::lastInsertId();* the **dblib** driver have a built-in solution?
