### ISSUE TITLE
How to start using Idiorm?

### ISSUE THREAD

**Issue by thebasix** [j4mie/idiorm#296]
How can I start using Idiorm in my project?

I installed it with composer and it is located in ./vendor/j4mie/idiorm/idiorm.php

I load it in my file like

```
require_once "vendor/autoload.php";
require_once 'vendor/j4mie/idiorm/idiorm.php';

ORM::configure(array(
    'connection_string' => 'mysql:host=localhost;dbname=dwa',
    'username' => 'root',
    'password' => 'root'
));

ORM::configure('return_result_sets', true); // returns result sets
```

I try to get the data from DB but I get nothing

`$result = ORM::for_table('nameoftable')->find_many();`

What am I doing wrong?

**Comment by treffynnon** [comment]
```php
require_once "vendor/autoload.php";

ORM::configure(array(
    'connection_string' => 'mysql:host=localhost;dbname=dwa',
    'username' => 'root',
    'password' => 'root',
    'return_result_sets' => true,
));

$result = ORM::for_table('name_of_table')->find_many();
```
Should work. Also what is the exact error you're getting? If you're not seeing any errors then up the level of PHP error reporting.

**Comment by thebasix** [comment]
I get this error:

```
The localhost page isn’t working
localhost is currently unable to handle this request.
```

When I remove all that code, it's fine.

**Comment by treffynnon** [comment]
You need to increase your error reporting level or look into the
application logs for hints.

**Comment by thebasix** [comment]
This is what I get:

`Fatal error: Uncaught exception 'PDOException' with message 'could not find driver' in /var/www/html/lab4/vendor/j4mie/idiorm/idiorm.php:255 Stack trace: #0 /var/www/html/lab4/vendor/j4mie/idiorm/idiorm.php(255): PDO->__construct('pdo_msql:host=l...', 'root', 'root', NULL) #1 /var/www/html/lab4/vendor/j4mie/idiorm/idiorm.php(237): ORM::_setup_db('default') #2 /var/www/html/lab4/proizvodi.php(41): ORM::for_table('proizvodi') #3 {main} thrown in /var/www/html/lab4/vendor/j4mie/idiorm/idiorm.php on line 255`

**Comment by peter-mw** [comment]
@thebasix msql driver? did you mean mysql?

check your connection string

**Comment by thebasix** [comment]
Still, when its mysql

`Fatal error: Uncaught exception 'PDOException' with message 'could not find driver' in /var/www/html/lab4/vendor/j4mie/idiorm/idiorm.php:255 Stack trace: #0 /var/www/html/lab4/vendor/j4mie/idiorm/idiorm.php(255): PDO->__construct('mysql:host=loca...', 'root', 'root', NULL) #1 /var/www/html/lab4/vendor/j4mie/idiorm/idiorm.php(237): ORM::_setup_db('default') #2 /var/www/html/lab4/proizvodi.php(41): ORM::for_table('proizvodi') #3 {main} thrown in /var/www/html/lab4/vendor/j4mie/idiorm/idiorm.php on line 255`

**Comment by treffynnon** [comment]
http://lmgtfy.com/?q=Uncaught+exception+%27PDOException%27+with+message+%27could+not+find+driver%27

**Comment by derainm** [comment]
Fatal error: Uncaught PDOException: could not find driver in /home/samakeur/www/libs/idiorm.php:328 Stack trace: #0 /home/samakeur/www/libs/idiorm.php(328): PDO->__construct('sqlite:data/dat...', NULL, NULL, NULL) #1 /home/samakeur/www/libs/paris.php(115): ORM::_setup_db('default') #2 /home/samakeur/www/libs/paris.php(371): ORMWrapper::for_table('enregistrement', 'default') #3 /home/samakeur/www/login/index.php(207): Model::factory('Enregistrement') #4 {main} thrown in /home/samakeur/www/libs/idiorm.php on line 328

**Comment by treffynnon** [comment]
http://lmgtfy.com/?q=Uncaught+exception+%27PDOException%27+with+message+%27could+not+find+driver%27
