### ISSUE TITLE
Unable to save information from join back to the original tables

### ISSUE THREAD

**Issue by SilentControl** [j4mie/idiorm#297]
Let's say that we join two tables. If we try to update a column from the second table and save the update, there is an error.

> PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such column: type'

Let's say that we have:
table1: **animal** with the fields: **id**(PK), **name**
table2: **state** with the fields **pid**, **type**
state.pid is a FK, referencing animal.id

If we join the two tables by id & pid and we update name and type (save), we get that certain error.
Is there a way to update both table1 and table2 by using the result return by the join?

[Example](https://gist.github.com/SilentControl/015cbdbb20f37324a48f1cb6056dc5d4)
@j4mie @treffynnon @anyone

**Comment by treffynnon** [comment]
This is a known and documented limitation. Idiorm can't know which table to
update - it is a common restriction that is also shared by desktop GUIs as
well as ORM libraries.
