### ISSUE TITLE
 Allowed memory size of 402653184 bytes exhausted (tried to allocate 80 bytes) in idiorm.php on line 1832

### ISSUE THREAD

**Issue by fainle** [j4mie/idiorm#298]
Allowed memory size of 402653184 bytes exhausted (tried to allocate 80 bytes) in vendor/j4mie/idiorm/idiorm.php on line 1832

**Comment by treffynnon** [comment]
This is not an error related to Idiorm. You're trying to load more information than your system can handle in memory.

Try putting a limit clause on your query - guessing you've got something that selects a lot of rows.
