### ISSUE TITLE
odbc:Driver={Microsoft Access Driver (*.mdb)} does not support lastInsertId()

### ISSUE THREAD

**Issue by eduardo-marcolino** [j4mie/idiorm#299]
I was working with a legacy mdb database and i got this message:

> "Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[IM001]: Driver does not support this function: driver does not support lastInsertId()' in ..

Here is my workarond:

Inside  [save()](https://github.com/j4mie/idiorm/blob/master/idiorm.php#L2014) method add this:

```php
if($db->getAttribute(PDO::ATTR_DRIVER_NAME) == 'pgsql') {
  //...
} elseif($db->getAttribute(PDO::ATTR_DRIVER_NAME) == 'odbc') {
  self::_execute('SELECT @@IDENTITY AS lastID', array(), $this->_connection_name);
  $statement = self::get_last_statement();
  $row = $statement->fetch(PDO::FETCH_ASSOC);
  $this->_data[$this->_get_id_column_name()] = $row["lastID"];

} else {
  //...
```

**Comment by kalmi** [comment]
The odbc driver does not implement lastInsertId in general.

I was using Microsoft's ODBC Driver 13 for SQL Server for Linux, and ran into the same issue. I ended up implementing a similar workaround. I added 
`$query[] = 'OUTPUT INSERTED.'.$this->_quote_identifier($this->_get_id_column_name());`
before the following line in _build_insert: 
`$query[] = "VALUES";`

I also forced the use of the pgsql brach in `save`.
