### ISSUE TITLE
Persistent "LIMIT 1" after count() call on find_many()

### ISSUE THREAD

**Issue by giorgiomarzianidepaolis-was** [j4mie/idiorm#302]
Even it's not the cleanest way to do _(I would recommend to execute find_many() and count items php side)_, this is weird:

`$res = ORM::for_table('foo')->where('bar', 'foo');`
`if ($res->count() > 0) {`
`    $results = $res->find_many();`
`}`

If you execute _find_many()_ after _count()_, it will return only first results. 
Debugging queries, I can see LIMIT 1 is included in the _find_many()_ query.

**Comment by treffynnon** [comment]
State is maintained on the ORM object. You need to have two separate ORM objects or clone the first like:

```php
$res = ORM::for_table('foo')->where('bar', 'foo');
$cnt = clone $res;
if ($cnt->count() > 0) {
    $results = $res->find_many();
}
```

**Comment by leo-combes** [comment]
I've the same problem. If you want not have a clone object, you can re assign the limit parameter with a large number, for example:

```
$res = ORM::for_table('foo')->where('bar', 'foo');
$cnt = clone $res;
if ($cnt->count() > 0) {
    $results->limit(200000);
    $results = $res->find_many();
}
```
