### ISSUE TITLE
Namespace please

### ISSUE THREAD

**Issue by fractalf** [j4mie/idiorm#303]
How about namespacing ORM to \j4mie\ORM or something?

**Comment by treffynnon** [comment]
Nope. Please see readme. This would be a BC and PHP 5.2 break.

**Comment by Ardakilic** [comment]
Anyone still using a [9-yeaar-old PHP version](https://secure.php.net/releases/#5.2.0), which is deprecated and full of security holes ?

I would rather break compatibility for such versions.

**Comment by treffynnon** [comment]
Idiorm supports 5.2 and this will not change as no BC breaks or new
features are permissible - again see the readme.

**Comment by fractalf** [comment]
Why don't you just make two branches or something?

master branch: php > 5.2 and add namespaces
legacy branch: <= 5.2

I just discovered this lib and love it, but like @Ardakilic says, it's kind of ridiculous to not evolve to modern syntax bacause someone use really old php versions.

2 branches and everyone is happy :)

**Comment by treffynnon** [comment]
See the readme.

**Comment by orlov0562** [comment]
Hi there!

Just for information for users who come here from the google:

I have faced with case when other class took ORM class name. To resolve this problem I have appended to the top of idiorm.php:

```
    namespace Idiorm;

    use ArrayAccess;
    use Countable;
    use IteratorAggregate;
    use Serializable;
    use PDO;
    use Exception;
...
```

After this you can use Idiorm from defined namespace:

```
    Idiorm\ORM::configure([
        'connection_string' => 'mysql:host='.$db['host'].';dbname='.$db['db'],
        'username' => $db['user'],
        'password' => $db['pass'],
    ]);

    $user = Idiorm\ORM::for_table('users')->where('id', 40)->find_one();

```
