### ISSUE TITLE
Multiple Connection Problem

### ISSUE THREAD

**Issue by FAYSVR** [j4mie/idiorm#311]
I'm trying to connect to two different databases, 
The logic is as follows; 
I connect to the login database on the login page when the site is opened, 
Different database information is kept for each user in this login database, I try to create a new connection with the  database information comes login database during user login...

This Login Database Connection named: 'remote';
***********************
ORM::configure("mysql:host=$db_host;dbname=$db_name" , NULL , 'remote');
ORM::configure('username', 'root', 'remote');
ORM::configure('password', '', 'remote');
ORM::configure('driver_options', array(PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8'), 'remote');
ORM::configure('return_result_sets', true , 'remote'); 
ORM::configure('logging', true , 'remote');
***********************

Running code when logging in
If the login check is successful ;

$db_host1 = $d['dbhost'];
$db_user1 = $d['dbuser'];
$db_password1 = $d['dbpass'];
$db_name1 = $d['dbname'];

ORM::configure("mysql:host=$db_host1;dbname=$db_name1", NULL , 'new');
ORM::configure('username', $db_user1 , 'new');
ORM::configure('password', $db_password1 , 'new');
ORM::configure('driver_options', array(PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8'), 'new');
ORM::configure('return_result_sets', true, 'new'); 
ORM::configure('logging', true, 'new');
**********************

named 'new' connection is not success, 
When I' running the active connection names;
****
print_r (ORM::get_connection_names());
****
Response;
Array ( [0] => remote ) 
******
Only one connection looks,

Pls Help Me, Where is my mistake???

**Comment by treffynnon** [comment]
Do you get any error messages?

**Comment by FAYSVR** [comment]
No , There are no error messages..

**Comment by FAYSVR** [comment]
No , There are no error messages..
---

iPhone'umdan g?nderildi

Simon Holywell <notifications@github.com<mailto:notifications@github.com>> ?unlar? yazd? (15 Ara 2016 03:01):


Do you get any error messages?

-

**Comment by FAYSVR** [comment]
Hi,
I'm waiting for an answer to this question,
Please..

**Comment by treffynnon** [comment]
Well I've not seen this problem before. It worked for me when I last tested
it. Have you got error reporting turned on? Have you watched your database
server logs during connection?

**Comment by FAYSVR** [comment]
I solved the problem. It was not because I wrote second connection codes on the login controller page, 
I passed it to the boot page, Now two connections are seems..
Thank you.
