### ISSUE TITLE
How to create central connection manager?

### ISSUE THREAD

**Issue by navid-dada** [j4mie/idiorm#312]
I want to create multiple repository class which are responsible for CRUD opration on my database entities. How can i create a connection and keep alive it for all of my application live cycle? Is there any best practice?

**Comment by tag** [comment]
This question is better suited for StackOverflow than as an issue ticket or feature request.

In addition, managing connections is best left to libraries, unless you have an absolute need for such a thing. And unless you are running a massive high-traffic site (e.g., Twitter), chances are you won't need such a thing (YAGNI).

Lastly, this is outside the scope of Paris/Idiorm.

**Comment by navid-dada** [comment]
I add [this ](http://stackoverflow.com/questions/41407044/how-to-create-an-data-repository-for-idiorm) question to the SO but others down vote me... and there is no answer
