### ISSUE TITLE
Update object after save

### ISSUE THREAD

**Issue by aless673** [j4mie/idiorm#313]
Hi, 

I have a lot of default values managed by postgres and after a initial save my object does not get updated with postgres default values. I need to use find_one again to get those default values.

Is there an other way ?

**Comment by treffynnon** [comment]
This sounds like expected behaviour. How would you expect to get the
database's record without querying for it? The idiorm object only knows
what you've told it until you query the database again.

**Comment by aless673** [comment]
The idiorm object is updated after the first save only on its id. It could be updated for any fields, or at least the save function could return the db's record.
It looks weird to ask the record just after its creation.

**Comment by treffynnon** [comment]
Using last insert ID to get the auto increment ID is very different to
fetching a record and updating the entire model.

If you really want this behavior then write a wrapper around idiorm that
does the insert and then the fetch. I would advise against it however.

A few reasons this would never appear in Idiorm:

- the record could be very large and undesirable to fetch
- it's a potentially wasted query
- systems regularly just need to insert data fast and query with reports
later
- it's unnecessary and potentially baffling magic
- it's a particular use case and not a universally useful pattern

**Comment by aless673** [comment]
There could be a function to update the record (maybe $obj->fetch()). It would be less disturbing when reading the code.

**Comment by treffynnon** [comment]
If you really like the idea then write a wrapper - this will not be going
into idiorm because it doesn't meet the principles of simplicity that
idiorm was set out on and there is also a feature freezer in place and only
maintenance patches are accepted.
