### ISSUE TITLE
Prompt how better to fulfill such a request to the database?

### ISSUE THREAD

**Issue by visavi** [j4mie/idiorm#314]
Prompt how better to fulfill such a request to the database?
UPDATE `table` SET `count`=`count`+1 WHERE `id`=1;

whether it is possible to do this without using the code below?
$table = ORM::for_table('table')->find_one(1);
example return table->count = 55;
... in another script or location, then insert occurred elsewhere and for example the number was 70 ...

// $table->count = 55 + 1 
$table->count = $table->count + 1;
$table->save();  // 56

and according to the normal should be 71

because as long as we get the object, the number can be changed in the interval
And if all wrapped in a transaction that is too much code

**Comment by treffynnon** [comment]
For something like UPDATE table SET count=count+1 WHERE id=1 you've got two
options.

You can use the ORM::raw_execute method/shortcut:
https://github.com/j4mie/idiorm/commit/f6d786167b9e2a14ebcdb537744b2df1b03ebd00

Or you can use get_db() to get the underlying PDO instance:
https://github.com/j4mie/idiorm/issues/20

**Comment by visavi** [comment]
There is a way to
```
$user = User::find_one(1);
$user->set_expr('money', 'money+1');
$user->save();
```

**Comment by treffynnon** [comment]
I thought you wanted to avoid the intermediary object and do it all in one
atomic call though? That method uses two queries and an object of course.

**Comment by visavi** [comment]
Is there a way to get the property without prior request,
$user->set_expr('money', 'money+1');   because it returns ...  $user->money  // 'money+1'

**Comment by treffynnon** [comment]
Yes, see my first answer.

Your pseudo code won't work the ORM must fetch before save otherwise you're
creating a new record.

**Comment by treffynnon** [comment]
What you're trying to achieve here is not something idiorm is designed to
do. It's part of the less used 20% the readme talks about. Still it does
offer a way round like I illustrated in my previous answer.
