### ISSUE TITLE
Query execution time

### ISSUE THREAD

**Issue by visavi** [j4mie/idiorm#315]
Sometimes during query output incorrectly displays runtime
echo 1485353496.7378 - 1485353496.7377;   // 9.9897384643555E-5
echo 1485353496.7383 - 1485353496.7382;  // 0.00010013580322266

this is probably due to some feature in PHP
Please correct https://github.com/j4mie/idiorm/blob/master/idiorm.php#L504

**Comment by treffynnon** [comment]
This looks perfectly acceptable to me given that they're very small
floating point numbers. You expect to get numbers in the exponential form.

You can use sprintf() with %f to print it for humans.

See http://php.net/manual/en/language.types.float.php
