### ISSUE TITLE
How to drop tables ?

### ISSUE THREAD

**Issue by DeeJaVu** [j4mie/idiorm#317]
Hello i am migrating my old code using idiorm but i have trouble migrating it

this is my old code

```php
            $res = mysql_query("SHOW TABLES");
            
            if ($res && mysql_num_rows($res)) {
                while ($s = mysql_fetch_assoc($res)) {
                    $table_name = array_pop($s);
                    if ($table_name) {
                        mysql_query("DROP TABLE $table_name");
                    }
                }
            }
```

and this is the new one

```php
            $res = ORM::raw_execute("SHOW TABLES");

            if ($res && count($res) > 0) {
                foreach ($res as $s) {
                    $table_name = array_pop($s);
                    if ($table_name) {
                        ORM::raw_execute("DROP TABLE $table_name");
                    }
                }
            }
```

but i get `Invalid argument supplied for foreach()`

how can i foreach and drop all my tables ?

**Comment by treffynnon** [comment]
What does var_dump($res); give you?

**Comment by DeeJaVu** [comment]
@treffynnon it gives 1 meaning TRUE

**Comment by DeeJaVu** [comment]
@treffynnon it gives ` bool(true)`

**Comment by treffynnon** [comment]
No, it should give a boolean as per the documentation and the PHP PDO documentation (Idiorm uses PDO underneath).

Please see:

* https://github.com/j4mie/idiorm/blob/master/idiorm.php#L459
* https://github.com/j4mie/idiorm/blob/master/idiorm.php#L482
* https://secure.php.net/manual/en/pdostatement.execute.php

What you're trying to do would require implementing something like the method used internally by Idiorm - https://github.com/j4mie/idiorm/blob/master/idiorm.php#L1906

So it would look something like this:

```php
$res = ORM::raw_execute("SHOW TABLES");
$statement = ORM::get_last_statement();
$rows = array();
while ($row = $statement->fetch(PDO::FETCH_ASSOC)) {
    $table_name = array_pop($row);
    if ($table_name) {
        ORM::raw_execute("DROP TABLE $table_name");
    }
}
```

You need to be aware that there is a reason that `raw_execute()` isn't highlighted in the user documentation. You're essentially dropping down straight to PDO and not using Idiorm (except to manage your connection configuration). In the case above you're actually working directly against a `PDOStatement` object when calling `fetch` - https://secure.php.net/manual/en/pdostatement.fetch.php

Hope that helps to get you going.
