### ISSUE TITLE
After updating, I'm not getting the new field value

### ISSUE THREAD

**Issue by sanmayad** [j4mie/idiorm#323]
I recently added a new column to my table and then updated a form that submits/update new values to that table. This works fine. The values are being inserted to DB.

But then when retriving the data from DB still it's keeping the new column in dirty_state and not showing me any value at all for that column

My config:

ORM::configure('caching', true);
ORM::configure('caching_auto_clear', true);

**Comment by treffynnon** [comment]
Please include the exact code you're using to query, update and then query the record again.

**Comment by sanmayad** [comment]
Normally there's some old code which directly enters data with mysqli and then I use idiorm to fetch those data. Any query that's not passed through idiorm doesn't show on fetching. Is there a way just to stop data/state caching for now. Later I will debug the issue.

**Comment by treffynnon** [comment]
I am struggling to understand what you're actually doing here. Please include the exact code you're using to query with Idiorm and your full Idiorm configuration.

**Comment by sanmayad** [comment]
Sure 

The config is as follows:

require_once 'idiorm.php';
ORM::configure('caching', false);
ORM::configure('mysql:host=localhost;dbname=mydb');
ORM::configure('username', 'bduser');
ORM::configure('password', 'password');

ORM::configure('id_column_overrides', array(
    'tag' => 'tagid',
    'accounts' => 'aid',
    'companies' => 'compid',
    'invoices' => 'inv_id',
    'invoice_settings' => 'invoice_settings_id',
));

And this is the code:

**Part1:**
$transactions = ORM::for_table('accounts')
			->select_expr('SUM(received)','received')
			->select_expr('SUM(spent)','spent')
			->select('sdate')
			->select('syear')
			->select('smonth')
			->select('sday')
			->select('finhead')
			->group_by('sdate')
			->group_by('finhead')
			->where_equal('compid', $compid)
			->where_equal('smonth', $curmonth)
			->where_equal('syear', $curyear)
			->find_many();

But there is another file which inserts data to account table which uses traditional mysqli: 
**part 2:**
mysqli_query("$con","INSERT INTO accounts($toputin,nulltax,sfor,sproject,sdate,sday,smonth,syear,accounts,finhead,cid,contacts,goal,thetags) VALUES('$stotal','$nulltax','$sfor','$sproject','$sdate','$sday','$smonth','$syear','$account','$head','$cid','$client','$goal','$thetags')") or die("cannot execute the  2.1.a query");

So if I enter a row using Part 2 method, I can't fetch that particular row with part 1 code. But if I write Part 2 with idiorm and insert data, then I can see the data.

All the old data it's showing, but the new ones after the implementation.

**Comment by sanmayad** [comment]
Works fine with the new release though :)
