### ISSUE TITLE
Mysql for update

### ISSUE THREAD

**Issue by 117311730** [j4mie/idiorm#324]
How to do lock a unique row in mysql?

**Comment by tag** [comment]
Tips on row locking in MySQL:

* http://lmgtfy.com/?q=lock+row+mysql
* https://stackoverflow.com/questions/33800234/row-level-locking-in-mysql
* https://stackoverflow.com/questions/3878672/how-to-lock-a-single-row

As for doing it in Idiorm, the documentation is quite helpful. You'll need to use `raw_query()`:

* http://idiorm.readthedocs.io/en/latest/querying.html#raw-queries
* http://idiorm.readthedocs.io/en/latest/transactions.html
