### ISSUE TITLE
phpdebugbar

### ISSUE THREAD

**Issue by rhnkyr** [j4mie/idiorm#329]
Hello,

how can i use idiorm / paris with phpdebugbar?

Thanks in advance

**Comment by treffynnon** [comment]
I've never used it but it looks like you can. You will need to set it in
the idiorm configuration:
http://idiorm.readthedocs.io/en/latest/configuration.html#query-logger

**Comment by treffynnon** [comment]
I am guessing that this answered your question so closing.
