### ISSUE TITLE
How can I see the raw sql that Idiorm generated?

### ISSUE THREAD

**Issue by thinsoldier** [j4mie/idiorm#331]

**Comment by treffynnon** [comment]
You can't from PHP land just like when you use PDO directly -
https://stackoverflow.com/a/2411208?stw=2

Idiorm ships with its own query logging implementation that you can use,
but it emulates what the database/PDO does underneath.
http://idiorm.readthedocs.io/en/latest/configuration.html#query-logging

To see the actually queries that ran you'd have to refer to the
logging/history/journaling available in your database of choice.

**Comment by treffynnon** [comment]
I am guessing that this answered your question so closing.
