### ISSUE TITLE
Hello, a problem when primary key is not 'id'.

### ISSUE THREAD

**Issue by xtlsoft** [j4mie/idiorm#333]
I am now facing a problem.
The Primary Key in my table is 'pid' instead of 'id', and I don't have an 'id' key.
So I failed in writing data to that table.
This is the error message I got:
![image](https://user-images.githubusercontent.com/16159830/36060594-ced2232a-0e87-11e8-804c-e00cb1cc8630.png)
Can you fix this problem?
Thank you.

**Comment by treffynnon** [comment]
http://idiorm.readthedocs.io/en/latest/configuration.html#id-column
