### ISSUE TITLE
How to do an aggregate select sum with clause?

### ISSUE THREAD

**Issue by Marcelo7015** [j4mie/idiorm#334]
I have the following query:

SELECT sys_transactions.rdate, sys_transactions.payeeid, sys_payee.name, 
                           SUM(IF(sys_transactions.status = 'Paid', sys_transactions.dr, 0)) as paid,
                           SUM(IF(sys_transactions.status = 'Payable', sys_transactions.dr, 0)) as payable,
                           SUM(IF(sys_transactions.status = 'Unpaid', sys_transactions.dr, 0)) as unpaid,
                           SUM(IF(sys_transactions.status = 'Cancelled', sys_transactions.dr, 0)) as cancelled,
                           SUM(sys_transactions.dr) as total
                           FROM sys_transactions 
                               INNER JOIN sys_payee
                                   ON sys_transactions.payeeid = sys_payee.id
                           WHERE sys_transactions.rdate >= '2018-01-01'
                               AND sys_payee.id=34
                               GROUP BY sys_payee.name

Please, how do I put the query in Idiorm?

Thanks.

**Comment by tag** [comment]
That query has errors and won't run correctly. (You're selecting non-aggregated fields but not grouping by them.)

Generally, GitHub Issues are for bugs in the library. StackOverflow may be a better place for questions of this sort. You'll certainly have more people seeing your question there.
