### ISSUE TITLE
MySQL SSL Connection Support with Idiorm??

### ISSUE THREAD

**Issue by AaronSaikovski** [j4mie/idiorm#335]
There doesnt seem to be a way to use an SSL Certificate with Idiorm and MySQL.
or is there?

**Comment by treffynnon** [comment]
Yes, actually, there is:

http://idiorm.readthedocs.io/en/latest/configuration.html#pdo-driver-options

+

http://php.net/manual/en/ref.pdo-mysql.php#pdo-mysql.constants

Or

https://stackoverflow.com/a/9768753
