### ISSUE TITLE
where_id_in with joints is broken

### ISSUE THREAD

**Issue by kkrell2016** [j4mie/idiorm#346]
Hi
If i join 2 tables with the same pk named ID the where_id_is function works great.
But the where_id_in function doesn't rename the ID column to tablename.ID as where_id_is would do.

So the query fails.

**Comment by treffynnon** [comment]
Would you be able to look into submitting a pull request to patch this and/or add a regression test to work against?

**Comment by treffynnon** [comment]
Could you post some code demonstrating this I problem please?

**Comment by kkrell2016** [comment]
I am sorry that you have to wait so long.

I can't find the old code at the moment, but I had two tables with a column called ID. I try to remember.....
Let's say  table user and table company.
I have created a user-> left_outer_join company on user.company = company.id.
It occurred later on select_many, because id was ambiguous. I tried to select it with user.id, but no success.

**Comment by treffynnon** [comment]
Closing this as we've had no further reports - can reopen if needed.
