### ISSUE TITLE
config.php was changed as below with MySQL db thing

### ISSUE THREAD

**Issue by Github743** [j4mie/idiorm#355]
I have updated the config but no luck still getting the same error

Fatal error: Uncaught PDOException: could not find driver in C:\inetpub\wwwroot\VisualQuery-master\vendor\j4mie\idiorm\idiorm.php:253 Stack trace: #0 C:\inetpub\wwwroot\VisualQuery-master\vendor\j4mie\idiorm\idiorm.php(253): PDO->__construct('mysql:host=test...', 'root', '1234', NULL) #1 C:\inetpub\wwwroot\VisualQuery-master\vendor\j4mie\idiorm\idiorm.php(369): ORM::_setup_db('default') #2 C:\inetpub\wwwroot\VisualQuery-master\index.php(63): ORM::get_db() #3 {main} thrown in C:\inetpub\wwwroot\VisualQuery-master\vendor\j4mie\idiorm\idiorm.php on line 253

`<?php`
//////////////////////////////////////////////
// Database Configuration
//////////////////////////////////////////////

// edit database settings
$config['database_host'] = 'testdb';
$config['database_user'] = 'root';
$config['database_password'] = '1234';
$config['database_dbname'] = 'aimetadb';

//////////////////////////////////////////////
// user details who can login - You can also specify more than one user
//////////////////////////////////////////////

// user 1
$config['username'][] = 'admin';
$config['password'][] = 'admin';

// user 2
$config['username'][] = 'admin2';
$config['password'][] = 'admin2';
?>`

**Comment by treffynnon** [comment]
Are you using MySQL or MSSQL? The error message is telling you that you've not got a MySQL driver installed. You must have a database server of the correct type and a driver for PHP installed for the correct database type.

**Comment by Github743** [comment]
Ok will download https://dev.mysql.com/downloads/connector/j/5.1.html and try

**Comment by Github743** [comment]
no luck either

**Comment by treffynnon** [comment]
From the errors you have shared; I can be certain that this is not an issue
with Idiorm. You need support installing a database driver - please follow
the relevant manuals or getting started guides and ask for help on
stackoverflow.com instead. These github issues are for items directly
related to Idiorm only.
