### ISSUE TITLE
Release 1.5.7 not on packagist

### ISSUE THREAD

**Issue by redaxmedia** [j4mie/idiorm#361]
Seems like the package is **not auto-updated**.

https://packagist.org/packages/j4mie/idiorm

**Comment by treffynnon** [comment]
That's annoying. I'll take a look. Something must've changed in the last
couple of years!

**Comment by treffynnon** [comment]
Looks like composer needs its github hook reinstalled, but unfortunately I don't have access to do that on these repositories. So, I have manually triggered the packagist update via curl. It should now be available through composer for you. Thanks for letting me know.

**Comment by redaxmedia** [comment]
Thanks
