### ISSUE TITLE
Question about safety

### ISSUE THREAD

**Issue by Gianiibooy** [j4mie/idiorm#363]
Hi,
I have a small question.

Still i need to escape input when i use a raw query?
My example:
`$last_year_sales_sql = 'SELECT Sum(Money) from db.money_transfer where YEAR(date) = YEAR(CURRENT_DATE()) AND receiver_id = '.$_SESSION["logged_in"].'';

$last_year_sales = ORM::for_table('money_transfer')->raw_query($last_year_sales_sql)->find_one();`

Thank you

**Comment by treffynnon** [comment]
Yes, you definitely should always be using query parameter binding. Here is
an example using your code. I wrote this on my phone so hopefully there
aren't any errors.

```php
$last_year_sales_sql = '
  SELECT Sum(Money)
    FROM db.money_transfer
   WHERE YEAR(date) = YEAR(CURRENT_DATE())
     AND receiver_id = :id';

$last_year_sales =
  ORM::for_table('money_transfer')
    ->raw_query(
      $last_year_sales_sql,
      array('id' => $_SESSION["logged_in"])
    )
    ->find_one();
```

**Comment by treffynnon** [comment]
Yes, you definitely should always be using query parameter binding. Here is
an example using your code. I wrote this on my phone so hopefully there
aren't any errors.

```php
$last_year_sales_sql = '
  SELECT Sum(Money)
    FROM db.money_transfer
   WHERE YEAR(date) = YEAR(CURRENT_DATE())
     AND receiver_id = :id';

$last_year_sales =
  ORM::for_table('money_transfer')
    ->raw_query(
      $last_year_sales_sql,
      array('id' => $_SESSION["logged_in"])
    )
    ->find_one();
```

**Comment by treffynnon** [comment]
From what I can see you don't need to be using raw_query here anyway. Someone asked a very similar question yesterday. Please see https://github.com/j4mie/idiorm/issues/362 for examples and info.

**Comment by treffynnon** [comment]
OK, I am going to close this issue now. I assume that this extra information has got it working for you again.
