### ISSUE TITLE
Multiple connections - instances

### ISSUE THREAD

**Issue by jspasiuk** [j4mie/idiorm#364]
Hello again, 

I'm having some issues with multiple connections and some multiple instances of the ORM class. I don't know if this is supported or if this is the idea of using this library.
In the same app code, i have almost 1600 db, and i'm used to open a connection, run the statement, and close the connection.
Now than I'm looking to implement Idiorm, I don't know how to do such think, as the previous connection keeps open, this is a sample code from my app:

`    ORM::configure('mysql:host='.DB_SENDGRID_HOST.';dbname=' . DB_SENDGRID_DBNAME,null,'aws_ss');
    ORM::configure('username', DB_SENDGRID_USERNAME,'aws_ss');
    ORM::configure('password', DB_SENDGRID_PASSWORD,'aws_ss');
    
    ORM::configure('return_result_sets', true,'aws_ss');
    ORM::configure('logging', true,'aws_ss');

    return ORM::class;`

and then I'm using:

`$aws_connection::for_table('ses_events','aws_ss')->select('txt_evento')->select_expr('count(1)','cantidad')->where_in("mensaje_id",$statusConcat)->order_by_desc("cantidad");`

This method work, but I have to always tell the method "for_table" for which connection to use, is this correct? Can I just open and close the connection after each statement? 

For exampĺe, this line gives me the last connection but for the default connection name, previously used in other line of code:

`$aws_connection::get_last_query();`

**Comment by treffynnon** [comment]
If I am understanding correctly you should be able to achieve what you want by calling [`ORM::reset_db()`](https://github.com/j4mie/idiorm/blob/master/idiorm.php#L364) to disconnect all open DB connections in Idiorm. To remove any existing configuration you can call [`ORM::reset_config()`](https://github.com/j4mie/idiorm/blob/master/idiorm.php#L294)

**Comment by jspasiuk** [comment]
Yes! I check and the reset_config() before open a new configuration should work for me here. Is there any option maybe to asign ORM as an object? Something like:

`$myobject = new ORM();`

and then use that object as an instance of ORM

**Comment by treffynnon** [comment]
Not as far as I am aware. You can clone the ORM where it returns `this` though.

```php
$partial_query = ORM::for_table('foo');

$ordered = clone($partial_query);
$ordered_results = $ordered->order_by_desc('bar');

$filtered = clone($partial_query);
$filtered_results = $filtered->where_equals('bar', 'some-value');
```

**Comment by jspasiuk** [comment]
I ended up using `ORM::reset_config()` and it worked just fine, no mixing connections now.

Thanks for the reply as always!
