### ISSUE TITLE
need help please

### ISSUE THREAD

**Issue by hellracer** [j4mie/idiorm#377]
Hi,

Good day, I'm inheriting a small project made with idiorm, if I join two tables how can i get table1.id or table2.id it was not clear in the document, thanks in advance

**Comment by treffynnon** [comment]
You will need to alias the columns you're selecting with `select` or `select_many` - look for the alias docs on these links:

- https://idiorm.readthedocs.io/en/latest/querying.html#result-columns
- https://idiorm.readthedocs.io/en/latest/querying.html#shortcuts-for-specifying-many-columns
- https://stackoverflow.com/a/19189278
