### ISSUE TITLE
Is there a way to truncate a table with Idiorm?

### ISSUE THREAD

**Issue by codecowboy** [j4mie/idiorm#56]
I tried: 

ORM::for_table('jobs')->raw_query('TRUNCATE :jobs_table',array('jobs_table', 'jobs'));

**Comment by zmip** [comment]
```
$this->db->for_table('users')->raw_execute('TRUNCATE TABLE `users`');
```

**Comment by InkyThousand** [comment]
Thanks @zmip , its work!

**Comment by masroore** [comment]
`ORM::raw_execute('TRUNCATE TABLE `table_name`');`
